title: Manman Li's Homepage
page-top-title: Manman Li
top-section-bg-text: Accounting and Finance Management
home-subtitle: Manman Li&ensp;|&ensp; 李曼曼
copyright-text: '&copy; Manman Li 2025-2026. All Rights Reserved.'
